name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: hwdhyeon/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 8c52506927bbe804fc5f922a753ca26f79b97610
          TIMEZONE: Asia/Seoul
